# Generated by Django 4.0.2 on 2022-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppprint", "0002_alter_importjob_status_alter_visualizationjob_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importjob",
            name="proteome",
        ),
        migrations.AddField(
            model_name="importjob",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visualizationjob",
            name="sources",
            field=models.ManyToManyField(to="ppprint.ImportJob"),
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
        migrations.DeleteModel(
            name="Proteome",
        ),
    ]
