# Generated by Django 4.0.2 on 2022-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppprint', '0005_importjob_created_at_visualizationjob_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='importjob',
            name='messages',
            field=models.ManyToManyField(to='ppprint.Message'),
        ),
        migrations.AddField(
            model_name='visualizationjob',
            name='messages',
            field=models.ManyToManyField(to='ppprint.Message'),
        ),
    ]
